test on fetch

diff --git a/.github/workflows/on_repo_update.yml b/.github/workflows/on_repo_update.yml
--- a/.github/workflows/on_repo_update.yml
+++ b/.github/workflows/on_repo_update.yml
@@ -21,14 +21,12 @@ jobs:
         run: |
           FORK_OWNER=$(jq -r .fork <<< '${{ toJson(github.event.client_payload) }}')
           REPO_NAME=$(jq -r .repo <<< '${{ toJson(github.event.client_payload) }}')
-          echo "FORK_OWNER=$FORK_OWNER"
-          echo "REPO_NAME=$REPO_NAME"
           git remote add "${REPO_NAME}" https://github.com/${FORK_OWNER}/${REPO_NAME}.git
 
       - name: Fetch & merge from fork
         run: |
-          git fetch "${REPO_NAME}" main || { echo "Failed to fetch main branch"; exit 1; }
-          git merge --no-ff "${REPO_NAME}" -m "Auto-merge from ${FORK_OWNER}/${REPO_NAME}"
+          git fetch "${REPO_NAME}" master || { echo "Failed to fetch main branch"; exit 1; }
+          git merge --no-ff "refs/remotes/${REPO_NAME}/master" -m "Auto-merge from ${FORK_OWNER}/${REPO_NAME}"
 
       - name: Push changes
         run: git push origin main
